// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPepraO0NUTvsfntNb6iOIS5li8tjXEsw',
    appId: '1:953226139203:web:851110d4c24b0f6848e6f6',
    messagingSenderId: '953226139203',
    projectId: 'get-user-dc086',
    authDomain: 'get-user-dc086.firebaseapp.com',
    storageBucket: 'get-user-dc086.appspot.com',
    measurementId: 'G-JQ9NLNR2R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRFkFkuvLp843Dhxmic1M7bd2AmfLTA8',
    appId: '1:953226139203:android:f475eb00193c698148e6f6',
    messagingSenderId: '953226139203',
    projectId: 'get-user-dc086',
    storageBucket: 'get-user-dc086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP9nRE_alw6S_9ok6I05FB1wKA7GdDvf0',
    appId: '1:953226139203:ios:4d48bf2df417248048e6f6',
    messagingSenderId: '953226139203',
    projectId: 'get-user-dc086',
    storageBucket: 'get-user-dc086.appspot.com',
    iosClientId: '953226139203-u30j2qtlen5531bln9d6im2q2jcur72u.apps.googleusercontent.com',
    iosBundleId: 'com.example.getUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP9nRE_alw6S_9ok6I05FB1wKA7GdDvf0',
    appId: '1:953226139203:ios:19fe6c273cd11c5d48e6f6',
    messagingSenderId: '953226139203',
    projectId: 'get-user-dc086',
    storageBucket: 'get-user-dc086.appspot.com',
    iosClientId: '953226139203-42a4besgib4jkpfget57f1r1kbdsr6v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.getUser.RunnerTests',
  );
}
